#此工作流将构建一个Python应用程序，并在提交到默认分支时将其部署到Linux上的Azure Functions应用程序。
#
#此工作流假设您已经创建了目标Azure Functions应用程序。
#有关说明，请参见https://learn . Microsoft . com/en-us/azure/azure-functions/create-first-function-vs-code-python？pivots = python-mode-配置
#
#要配置此工作流:
# 1.在存储库中设置以下机密:
#-AZURE _ function app _ PUBLISH _ PROFILE
# 2.为您的配置更改环境变量。
#
#有关以下内容的更多信息:
# - GitHub为Azure采取的行动:https://github.com/Azure/Actions
# - Azure Functions动作:https://github.com/Azure/functions-action
# -发布配置文件:https://github . com/Azure/functions-action # using-Publish-Profile-as-deployment-credential-推荐
#-RBAC的Azure服务主体:https://github . com/Azure/functions-action # using-Azure-Service-Principal-for-RBAC-as-deployment-credential
#
#获取更多用于部署到Azure的GitHub操作工作流入门示例:https://GitHub . com/Azure/actions-workflow-samples/tree/master/function app

名字：名称：将Python项目部署到Azure函数应用程序

在：
推：
分支：["主要"]

env:
  AZURE_FUNCTIONAPP_NAME: 'your-app-name'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'       # set this to the path to your function app project, defaults to the repository root
  PYTHON_VERSION: '3.9'                     # set this to the python version to use (e.g. '3.6', '3.7', '3.8')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    # If you want to use Azure RBAC instead of Publish Profile, then uncomment the task below
    # - name: 'Login via Azure CLI'
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }} # set up AZURE_RBAC_CREDENTIALS secrets in your repository

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }} # Remove publish-profile to use Azure RBAC
        scm-do-build-during-deployment: true
        enable-oryx-build: true
