名字：名称:IPTV All
推：
分支：
-主要的
工作：
建设：
连续运行:Ubuntu-最新版
步伐：
结账代码
动作/签出@v2
-名字：设置计算机编程语言
操作/设置-python@v2
随着：
大蟒版本:3.x
-名字：安装依赖项
奔跑:画中画安装硒请求
-名字：安装Chrome网络驱动程序
奔跑：
最新的CHROMEDRIVER版本=120.0.6099.109
curl-sS-o chrome driver _ Linux 64 . zip“https://edge dl。我。gvt 1。com/edge dl/chrome/chrome-用于测试/120。0 .6099 .109/Linux 64/chrome无头外壳-Linux 64。zip "
须藤解压铬驱动程序_ Linux 64。zip-d/usr/local/bin
rm chromedriver_linux64.zip
-名字：设置铬驱动器路径
奔跑：
sudo ln-SF/usr/local/bin/chrome无头外壳Linux 64/chrome无头外壳/usr/local/bin/chrome驱动程序
sudo chmod+x/usr/local/bin/chrome驱动程序
-名字：运行脚本
奔跑:python ${{github.workspace}}/IPTV.py
-名字：提交更改
奔跑：
饭桶配置-本地用户。电子邮件"805465364@qq.com"
饭桶配置-本地用户名你自己的开源代码库用户名"
饭桶添加。
饭桶提交*。txt -m“添加生成的文件"
饭桶推出
