名字：IPTV全部
在：
推：
branches：
-主要的
工作：
建设：
连续运行：Ubuntu-最新版
步伐：
-名字：结账代码
使用：动作/签出@v2
-名字：设置Python
使用：操作/设置-python@v2
随着：
python版本：3.x
-名字：安装依赖项
奔跑：pip安装selenium请求
-名字：安装Chrome WebDriver
奔跑：
最新的CHROMEDRIVER版本=120.0.6099.109
curl-sS-o chrome driver _ Linux 64 . zip“https://edge dl . me . gvt 1 . com/edge dl/chrome/chrome-for-testing/120 . 0 . 6099 . 109/Linux 64/chrome-headless-shell-Linux 64 . zip“
sudo unzip chrome driver _ Linux 64 . zip-d/usr/local/bin
rm chromedriver_linux64.zip
-名字：设置chromedriver路径
奔跑：
sudo ln-SF/usr/local/bin/chrome-headless-shell-Linux 64/chrome-headless-shell/usr/local/bin/chrome driver
sudo chmod+x/usr/local/bin/chrome driver
-名字：运行脚本
奔跑：python ${{github.workspace}}/IPTV.py
-名字：提交更改
奔跑：
git配置-本地用户。电子邮件“805465364@qq.com"
git配置-本地用户名"wuxi201314"
git添加。
git提交*。txt -m“添加生成的文件”
git推出
